84 approval request admin view
UCDavisLibrary/ucdlib-travel pull request #102
Opened 2024-09-14 00:28 UTC by mjwdavis

The status filter is in place, but I'm running into a block when attempting to load the employee filter. #84

2024-09-16 14:11 UTC, spelkey-ucd requested changes
looking good so far.

what's the block with the employees filter? setting up store,service, and model methods? I recommend starting with the [store](https://github.com/ucd-library/cork-app-utils?tab=readme-ov-file#basestore), and then working backwards to the [service](https://github.com/ucd-library/cork-app-utils?tab=readme-ov-file#baseservice), and then the [model](https://github.com/ucd-library/cork-app-utils?tab=readme-ov-file#basemodel). It is a lot of boilerplate, so copilot can help a lot here.

fyi, the `os-developers` slack channel is an excellent resource for questions about the `cork-app-utils` package since we all use it.

2024-09-16 14:11 UTC, spelkey-ucd commented on src/api/employee.js
> +  api.get('/employees', protect('hasBasicAccess'), async (req, res) => {
this is an admin section, so `hasBasicAccess` is too loose of authorization

2024-10-09 16:43 UTC, spelkey-ucd requested changes

2024-10-09 16:43 UTC, spelkey-ucd commented on src/client/js/pages/admin/app-page-admin-approval-requests.js
> +      return { state: 'error', payload: [] };  // Return error state in case of failure
this is badness. most of this method is unnecessary. the service should handle the state (it does so automatically), not the element.

and then to set your `employeesInDB` property, you can use the `_onEmployeesFetched` callback

2024-10-09 16:43 UTC, spelkey-ucd commented on src/lib/db-models/employee.js
> +    const res = await pg.pool.query('SELECT * FROM employee');
always use the method `pg.query` - it just wraps pool in a try/catch. so if the db query fails for some reason, the whole app isn't taken down.

2024-10-09 16:43 UTC, spelkey-ucd commented on src/client/js/pages/admin/app-page-admin-approval-requests.js
> +      // Process approval requests
you dont need this `process approval requests` block. you already are doing this in `_onApprovalRequestsRequested`

2024-10-09 16:43 UTC, spelkey-ucd commented on src/lib/cork/stores/ApprovalRequestStore.js
> +      APPROVAL_REQUESTS_FILTERS_FETCHED: 'approval-requests-filters-fetched'
dont need this

2024-10-09 16:43 UTC, spelkey-ucd commented on src/lib/cork/stores/ApprovalRequestStore.js
> +  _setApprovalRequestsFiltersFetchedState(state) {
dont need this

2024-10-17 00:14 UTC, mjwdavis commented on src/client/js/pages/admin/app-page-admin-approval-requests.js
> +      // Process approval requests
block removed

2024-10-18 17:14 UTC, mjwdavis commented on src/client/js/pages/admin/app-page-admin-approval-requests.js
> +      return { state: 'error', payload: [] };  // Return error state in case of failure
I noticed that you referenced _onEmployeesFetched, but I wanted to clarify that this function doesn’t exist in the project. The employee data is managed via this.store.data.allEmployees, which automatically handles the state for me. As a result, manually updating the state with a callback function is unnecessary, and the service handles this automatically. Let me know if I misunderstood any part of your feedback!

2024-10-23 20:22 UTC, spelkey-ucd approved these changes
looks good. just a couple things that i noted, but ill make those changes after the pr is merged.

2024-10-23 20:22 UTC, spelkey-ucd commented on src/lib/db-models/employee.js
> +    return res.res;
you arent actually handling the error state here. in your api file you correctly check for the error state with `    if ( apiResult.error ) `.

in this method, you need to just return `res` and then in your api, if no error, return `apiResult.res.rows` instead of just `apiResult.rows`

2024-10-23 20:22 UTC, spelkey-ucd commented on src/client/js/pages/admin/app-page-admin-approval-requests.js
> +    this.EmployeeModel.getAllEmployees();
this should be in your `getPageData` call. putting it here, means that the http response will occur when the code is loaded - even if the user never vists this page.

2024-10-23 20:24 UTC, merged