Integrate Keycloak Client #7
UCDavisLibrary/ucdlib-travel pull request #17
Opened 2024-04-11 20:57 UTC by mjwdavis

https://github.com/orgs/UCDavisLibrary/projects/196/views/1?pane=issue&itemId=59466753

2024-04-12 14:28 UTC, spelkey-ucd requested changes
Keycloak config looks good except you don't want "Client Authentication" checked (I unchecked it). That is only for auth flows that require a client secret. In SPAs, we do our auth on the browser-side which then passes the access token to the server in the API requests (check out the [client-side BaseService](https://github.com/UCDavisLibrary/ucdlib-travel/blob/main/src/lib/cork/services/BaseService.js#L28) and then [the API middleware](https://github.com/UCDavisLibrary/ucdlib-travel/blob/main/src/api/auth.js#L9) ). Client secrets are only for straight up server-side auth, otherwise the secret would be leaked in the browser.

![image](https://github.com/UCDavisLibrary/ucdlib-travel/assets/34284106/00c954f5-5f27-4a1e-aa2e-6ba449d7d987)

2024-04-12 14:28 UTC, spelkey-ucd commented on src/lib/serverConfig.js
> +    this.title = this.getEnv('APP_TITLE', 'UC Davis Library Travel App');
I have a separate issue for this. Debbie had a different name in mind.

2024-04-12 14:28 UTC, spelkey-ucd commented on src/lib/utils/AccessToken.js
> +    get hasReportAccess(){
we also want admin to be able to access reports

2024-04-12 14:28 UTC, spelkey-ucd commented on src/lib/utils/AccessToken.js
> +      return this._inRoleList('report-access');
This would also grant access to the `report-access` realm role - we only want client.

2024-04-12 23:36 UTC, mjwdavis commented on src/lib/utils/AccessToken.js
> +    get hasReportAccess(){
Added roles as array to hasAdminAccess.

2024-04-12 23:36 UTC, mjwdavis commented on src/lib/utils/AccessToken.js
> +      return this._inRoleList('report-access');
removed function

2024-04-12 23:37 UTC, mjwdavis commented on src/lib/serverConfig.js
> +    this.title = this.getEnv('APP_TITLE', 'UC Davis Library Travel App');
Updated title to "UC Davis Library Travel, Training, and Professional Development" per Figma design

2024-04-15 14:27 UTC, spelkey-ucd requested changes

2024-04-16 20:19 UTC, merged