Sb approver model
UCDavisLibrary/ucdlib-travel pull request #33
Opened 2024-05-02 21:08 UTC by sbagg

#22 and #23

2024-05-03 15:06 UTC, spelkey-ucd requested changes

2024-05-03 15:06 UTC, spelkey-ucd commented on src/lib/db-models/approverType.js
> +          await client.query('COMMIT');
You also want to ensure that the employee exists in the employee table, and 
1. if they dont, insert them
2. if they do, update their first and last name

2024-05-03 15:06 UTC, spelkey-ucd commented on src/lib/db-models/approverType.js
> +        if ( Object.keys(approverEmployee).length === 0 ) return await pg.query(text, [...updateClause.values, id]);
if an employee list is empty, you have to remove all existing relationships.

2024-05-03 15:06 UTC, spelkey-ucd commented on src/lib/db-models/approverType.js
> +       async update(data){
same basic comments as `create` method

2024-05-09 20:15 UTC, spelkey-ucd requested changes

2024-05-09 20:15 UTC, spelkey-ucd commented on src/lib/db-models/approverType.js
> +          let employeeApproverCheck = await this.approverEmployeeCheck(approverTypeId);
this should be part of transaction. that method opens up a new client.

in fact, it doesn't really need to be its own method. you can just delete all employees:
```query(`DELETE FROM approver_type_employee WHERE approver_type_id = ($1)`, [approverTypeId]);```

you dont need to check if they exist first, if they don;t this DELETE statement will do nothing

2024-05-09 20:15 UTC, spelkey-ucd commented on src/lib/db-models/approverType.js
> +              toEmployeeUpdate['approval_order'] = a.approvalOrder;
again, approval order should be array index

2024-05-09 20:15 UTC, spelkey-ucd commented on src/lib/db-models/approverType.js
> +      async query(kwargs){
also, you should return the employees array:
```
{
  ...everything from `approver_type`,
employees: [
{firstName: 'Foo', lastName: 'Bar', kerberos: 'foobar'}
]
}
```

see `fundingSource.get` for example of query. (chatgpt wrote most of it. just plug in the database table schemas in, and it will get you 99% of the way there)

2024-05-09 20:15 UTC, spelkey-ucd commented on src/lib/db-models/approverType.js
> +            out.res.push(r);
instead of combining apples with oranges in your out.res array, just call `this.query({id: approverTypeId})` after your try block.

it adds an extra db call (less performance), but i think thats a good tradeoff for the simplicity.

2024-05-15 18:43 UTC, spelkey-ucd requested changes
almost there, i swear!

2024-05-15 18:43 UTC, spelkey-ucd commented on src/lib/db-models/approverType.js
> +        json_agg(json_build_object(
the only thing you need to `json_agg` is the employees array.

so, your sql should look something like
```
SELECT
ap.*,
  json_agg( json_build_object(
      'kerberos', emp.kerberos,
      'firstName', emp.first_name,
      'lastName', emp.last_name
    )) AS employees
...
```

this way, you dont have to redefine all your columns and can use `entityFields.toJsonArray` instead

2024-05-15 18:43 UTC, spelkey-ucd commented on src/lib/db-models/approverType.js
> +        async queryFormat(array){
doc string doesnt match method

2024-05-15 18:43 UTC, spelkey-ucd commented on src/lib/db-models/approverType.js
> +            }
it's better to run your validations before you create a new client. just move this block to the top of the method.

2024-05-15 18:43 UTC, spelkey-ucd commented on src/lib/db-models/approverType.js
> +            const noKerberos = approverEmployee.every(a => ( a.employee.kerberos && a.employee.kerberos != '' && a.employee.kerberos != undefined))
move noKerberos validation to own method and add to the `customValidation` prop on the `employees` `entityFields`. e.g.

`{dbName: 'employees', jsonName: 'employees', customValidation: this.validateEmployees.bind(this)},`

2024-05-15 18:43 UTC, spelkey-ucd commented on src/lib/db-models/approverType.js
> +            const res = await pg.query(sql, data.values);
use the client that you created for the transaction - not the generic pool.

```
const res = await client.query(sql, data.values);
```

see alert box at https://node-postgres.com/features/transactions

2024-05-15 18:43 UTC, spelkey-ucd commented on src/lib/db-models/approverType.js
> +                if ( !Object.keys(toEmployeeCreate).length ){
you check for kerberos field above, so you dont need this return.

also, you can assume approverTypeId and kerberos exists, so you can do:

```
const toEmployeeCreate = {
  'approver_type_id' : approverTypeId, 
  'employee_kerberos': a.employee.kerberos
}
```

2024-05-15 18:43 UTC, spelkey-ucd commented on src/lib/db-models/approverType.js
> +       async update(data){
most of my comments on the `create` method apply to `update` as well

2024-05-15 21:37 UTC, sbagg commented on src/lib/cork/models/AdminApproverTypeModel.js
> +      if (state.state === 'loaded') this.store.data.create = {}
What do you mean by blow out? Like expand it to full if/else statement?

2024-05-15 21:38 UTC, sbagg commented on src/lib/cork/models/AdminApproverTypeModel.js
> +      if (state.state === 'loaded') this.store.data.update = {}
Same question as above

2024-05-16 20:23 UTC, merged