14 component library employee search basic
UCDavisLibrary/ucdlib-travel pull request #40
Opened 2024-05-10 01:48 UTC by mjwdavis

#14

2024-05-13 17:49 UTC, spelkey-ucd requested changes

2024-05-13 17:49 UTC, spelkey-ucd commented on src/client/js/components/ucdlib-employee-search-basic.js
missing doc string.

include:
- description
- description of properties
- events to listen for

2024-05-13 17:49 UTC, spelkey-ucd commented on src/client/js/components/ucdlib-employee-search-basic.js
> +    createRenderRoot() {
use MainDomElement mixin instead

2024-05-13 17:49 UTC, spelkey-ucd commented on src/client/js/components/ucdlib-employee-search-basic.js
> +    _renderResult(result){
move to template file

2024-05-13 17:49 UTC, spelkey-ucd commented on src/client/js/components/ucdlib-employee-search-basic.js
> +      let name = `${result.first_name} ${result.last_name}`.replace(/</g, '&lt;').replace(/>/g, '&gt;');
dont worry about highlighting the search term

2024-05-13 17:49 UTC, spelkey-ucd commented on src/client/js/components/ucdlib-employee-search-basic.js
> +        <div class='muted'>${result.title}</div>
add department

2024-05-13 17:49 UTC, spelkey-ucd commented on src/client/js/components/ucdlib-employee-search-basic.js
> +    _onSelect(result){
employee's kerberos should be the selected value.

And then if the element attribute is updated e.g.
```
<ucdlib-employee-search-basic selected='akerberos'></ucdlib-employee-search-basic>
```

the component will use `EmployeeModel.getIamRecordById('akerberos')` to go fetch the record, and update the element state:
1. set selected text (their name) and selected status OR
2. set error status if employee doesn't exist

2024-05-13 17:49 UTC, spelkey-ucd commented on src/client/scss/components/employee-search-basic.scss
> +    // max-width: 500px;
rm commented out code

2024-05-14 20:26 UTC, mjwdavis commented on src/client/js/components/ucdlib-employee-search-basic.js
added documentation

2024-05-14 20:26 UTC, mjwdavis commented on src/client/js/components/ucdlib-employee-search-basic.js
> +    createRenderRoot() {
swapped out

2024-05-14 20:26 UTC, mjwdavis commented on src/client/js/components/ucdlib-employee-search-basic.js
> +    _renderResult(result){
moved to template file

2024-05-14 20:26 UTC, mjwdavis commented on src/client/js/components/ucdlib-employee-search-basic.js
> +      let name = `${result.first_name} ${result.last_name}`.replace(/</g, '&lt;').replace(/>/g, '&gt;');
removed highlighting function

2024-05-14 20:28 UTC, mjwdavis commented on src/client/js/components/ucdlib-employee-search-basic.js
> +        <div class='muted'>${result.title}</div>
added department to function and helper function to determine department from result

2024-05-14 20:30 UTC, mjwdavis commented on src/client/js/components/ucdlib-employee-search-basic.js
> +    _onSelect(result){
async _onSelect(result){
      this.selectedText = `${result.first_name} ${result.last_name}`;
      const iamresult = await this.EmployeeModel.getIamRecordById(result.user_id)
      this.selectedObject = iamresult.payload;
      this.dispatchEvent(new CustomEvent('select', {
        detail: iamresult
      }));
    }

2024-05-14 20:30 UTC, mjwdavis commented on src/client/scss/components/employee-search-basic.scss
> +    // max-width: 500px;
rm'd

2024-05-16 14:01 UTC, spelkey-ucd requested changes

2024-05-16 14:01 UTC, spelkey-ucd commented on src/client/js/components/ucdlib-employee-search-basic.tpl.js
> +  let name = `${result.first_name} ${result.last_name}`.replace(/</g, '&lt;').replace(/>/g, '&gt;');
no need to remove `<` and `>`. If they exist, Lit will handle them automatically.

2024-05-17 05:26 UTC, mjwdavis commented on src/client/js/components/ucdlib-employee-search-basic.js
> +      const iamresult = await this.EmployeeModel.getIamRecordById(result.user_id)
This doesn't make sense to me. If there isn't a result.user_id, then we don't have anything to search getIamRecordById with, since it uses a kerberos to search. I don't know why we have to listen to a value change in the lifecycle for this. If we're checking the value of r in line 135, then we should have checked that we had the correct data when we first retrieved it.

2024-05-17 13:40 UTC, spelkey-ucd commented on src/client/js/components/ucdlib-employee-search-basic.js
> +      const iamresult = await this.EmployeeModel.getIamRecordById(result.user_id)
you need to give a programmer a way to set the initial state of the element.

In a normal select element, this is achieved via the `selected` property:
```
<select>
 <option value='foo'>Foo</option>
 <option value='bar'>Bar</option>
 <option value='baz' selected>We want this to show to the user when they load the page</select>
</select>
```

We need to be able to do the same thing with this element:
```
<ucdlib-employee-search-basic selected-value=${kerberos}></ucdlib-employee-search-basic>
```

which means, listening for a change in that value, and retrieving the employee record when it changes and is different from the `selectedObject`.

2024-05-21 20:37 UTC, spelkey-ucd requested changes

2024-05-21 20:37 UTC, spelkey-ucd commented on src/client/js/components/ucdlib-employee-search-basic.js
> +    }
1. `shouldUpdate` is meant to be called to determine whether an update cycle is required - aka to specify which property changes should cause updates, if you need to customize that. You want `willUpdate`, which is meant for computing property values that depend on other properties and are used in the rest of the update process.
2. You only want to do your fetch if selectedValue != selectedObject.user_id and if selectedValue is not empty
3. selectedText also needs to be set
4. Do special handling for if employee is missing (as opposed to a network error) - tell the user that the employee is not in Library directory system.

2024-05-21 20:37 UTC, spelkey-ucd commented on src/client/js/components/ucdlib-employee-search-basic.js
> +      this.selectedObject = {};
add `this.selectedValue = ''`

2024-05-21 20:37 UTC, spelkey-ucd commented on src/client/js/components/ucdlib-employee-search-basic.tpl.js
> +          </div>
add red X icon for error state

2024-05-22 13:53 UTC, spelkey-ucd requested changes

2024-05-22 13:53 UTC, spelkey-ucd commented on src/client/js/components/ucdlib-employee-search-basic.js
> +          if (iamobject.payload.total) { // if multiple results are returned
we want to handle a 404 - the employee doesn't exist.
so, if the element is set as 
```<ucdlib-employee-search-basic .selectedValue='foobar'></ucdlib-employee-search-basic>```
then the user will see that the element is in error state.

2024-05-22 13:53 UTC, spelkey-ucd commented on src/client/js/components/ucdlib-employee-search-basic.js
> +          this.noIam = true;
We want to differentiate between a generic error (aka something went wrong with the network request), and a 404 (the network success succeeded, but this user doesnt exist)

2024-05-22 13:53 UTC, spelkey-ucd commented on src/client/js/components/ucdlib-employee-search-basic.js
> +      }
You are emitting two `status-change` events.

and very importantly, you never clear the `this.noIam` status, so once it gets set, if the user searches for a new employee to replace the missing one, the noIam error will still display

2024-05-22 20:15 UTC, merged