Sb approver gui
UCDavisLibrary/ucdlib-travel pull request #43
Opened 2024-05-17 06:56 UTC by sbagg

Initial GUI for the updates.  This is without the employees search element to add to the element

2024-05-17 19:50 UTC, spelkey-ucd requested changes
In general, you can use the [line item page](https://github.com/UCDavisLibrary/ucdlib-travel/blob/dev/src/client/js/pages/admin/app-page-admin-line-items.js) as a template. it is very, very similar to what you need to make.

2024-05-17 19:50 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +      this._getApproverType();
rely on `_onAppStateUpdate` callback to get your data after edit/create/delete functions. it's more foolproof.

so, after your user's edits are successful, you will run
```
this._resetProperties();
this.AppStateModel.refresh();
```
, which will refire the app-state-update event

2024-05-17 19:50 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +  }
im confused by these properties. 

1. there is a discrepancy between what is here, and what is defined at top of file
2. imo, you really should only need two properties: `this.existingApprovers` and `this.newApprovers`

2024-05-17 19:50 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +  async _setLabel(value){
if you pass through your approverItem object as well, it will update regardless of it belongs to the `newApprover` or `existingApprover` e.g.

```
_setLabel(value, approver){
approver.label = value;
this.requestUpdate() // important because Lit doesn't automatically detect property changes to objects inside arrays
}
```

2024-05-17 19:50 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +    async _onNewSubmit(){
you can have your creation form and update form share the same callback by attaching the `approverTypeId` to the form as an attribute, and kill two birds with one stone.

```
_onNewSubmit(e){
e.preventDefault();
const approverTypeId = e.target.getAttribute('approver-type-id');
if ( approverTypeId ) {
  const approverType = this.approverTypes.find(a => a.approverTypeId === approverTypeId);
 this.ApproverModel.update(approverType);
} else {
this.ApproverModel.create(this.newApproverType);
}
}

```

also, a submit call should be attached to the form submit event, and not the button click:
```
<form @submit = ${this._onSubmit)>
</form>
```

2024-05-17 19:50 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +      document.querySelector(".textDescription").value = "";
querySelecting is usually an antipattern in Lit. Your template should automatically update based on the properties you define.

2024-05-17 19:50 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +        this._refreshProperties();
you should really only run `_refreshProperties` if your update was successful. e.g. if there is a validation problem, you will want to keep the user-entered values, so you can highlight them for correction.

use your model callbacks for this `_onApproverTypeCreated` and `_onApproverTypeUpdated`:
https://github.com/UCDavisLibrary/cork-app-utils?tab=readme-ov-file#litelement

2024-05-17 19:50 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.tpl.js
> +        in this section.
make this description a setting

2024-05-17 19:50 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.tpl.js
> +  let ap = approver;
just name your function param `ap`...

2024-05-17 19:50 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.tpl.js
> +              <span @click=${e => this._onEdit(e, ap)} class="user-icon"><i class="fa-solid fa-pen-to-square"></i></span>
1. move icons outside of the h3, so that they aren't super huge
2. I have a global class for icon buttons, which will take care of the hover effect, and use brand classes for the color

```
<a @click=${e => this._onDelete(ap)} class='icon-link double-decker'>
        <i class="fa-solid fa-trash-can"></i>
</a>

```

2024-05-17 22:51 UTC, sbagg commented on src/client/js/components/app-approver-type.tpl.js
> +  let ap = approver;
Lol your right I do not know why I did that

2024-05-20 17:23 UTC, sbagg commented
Still in progress with changes just needs a quick pit stop review

2024-05-20 19:08 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +    approver.label = value;
add `this.requestUpdate()` here

2024-05-22 15:01 UTC, spelkey-ucd requested changes

2024-05-31 14:57 UTC, spelkey-ucd requested changes
your validationHandler likely wasnt working because you didnt set it in `_onApproverTypeQueryRequest`

however, the two bigger problems are:
1. having `APPROVER_TYPE_QUERY_REQUEST` return an array instead of an object
2. your use of `this.approver`

2024-05-31 14:57 UTC, spelkey-ucd commented on src/lib/cork/models/AdminApproverTypeModel.js
> +    this.store.emit(this.store.events.APPROVER_TYPE_QUERY_REQUEST, [this.store.data.query[args],query]);
stay in the box and have a cork-app-utils event return an object, not an array. many things expect that `e.state` will contain the state of the request. e.g. `const hasError = d.some(e => e.status === 'rejected' || e.value.state === 'error');` when checking for an error

if you need the query in the event object, save it when writing to the store object: `this.store.data.query[args]`

2024-05-31 14:57 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +        approverType.validationHandler = new ValidationHandler(e)
remove this line.

`ValidationHandler` expects to receive PUT/POST cork-app-utils response.

2024-05-31 14:57 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +      this.initial = approver;
i dont understand the purpose of `this.initial` - it shouldn't be necessary

2024-05-31 14:57 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.tpl.js
> +  this.approver = approver;
`this.approver = approver;` is badness.

1. you shouldn't set properties in a render function. as a rule, render functions should only render - they should not have side effects.
2. More than one approverType can be set as `approver.editing`, so you could have some crossed wires going on by mapping to a single element property.
3. by creating another property, you are adding another potential point of failure. everything you need about the approverType is already saved in two spots: 1. in your existingApprovers array, and 2. in your AdminApproverTypeStore

Lose `this.approver`, and just set everything to the approver object in `existingApprovers`

2024-05-31 14:57 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.tpl.js
> +          ${this.approver.editing ? html`
if you are showing this form, by default `approver.editing` should be true - if it's not, you have bigger problems.

2024-05-31 14:57 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +      if ( e.error?.payload?.is500 ) {
a validation error will be a 400

2024-05-31 14:57 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +       async getPageData(){
`this.AdminApproverTypeModel.query(args);` should be here. it is required to render your page.

2024-05-31 14:57 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +    this.description = category.payload[0].defaultValue;
you already call `this.SettingsModel.getByCategory` in `getPageData`. 

you just need to do: `this.description =  this.SettingsModel.getByKey('approver_type_description')`
or you can just put that call directly in your template, and skip `this.description`

2024-05-31 14:57 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +    await this.AdminApproverTypeModel.query(args);
move to `getPageData`

2024-05-31 14:57 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +     _onApproverTypeFetched(e){
this isn't one of your store events

2024-05-31 14:57 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +    if ( e.state === 'error' ) {
if in `getPageData` the error state is already handled.

2024-05-31 14:57 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +    } else if ( e.state === 'loaded' && this.isEqual(query, {'status':'active'})) {
instead of `this.equal` use `urlUtils.queryStringFromObject`.

2024-05-31 14:57 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +    } else if ( e.state === 'loading' ) {
loading state is already handled.

2024-05-31 14:57 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +      approverArray.map((emp) => {
you also want to copy all the objects.

e.g. `emp = {...emp}`

otherwise, when a user edits the approverType using the form, they will also be changing the data in your `AdminApproverTypeStore`

ALSO, you need to set the validationHandler:

`emp.validationHandler = new ValidationHandler()`

2024-06-01 03:10 UTC, sbagg commented
I am still having an issue with the validation but I fixed your other corrections.  Error that keeps popping up is still the `TypeError: Cannot read properties of undefined (reading 'errorClass')`.

2024-06-03 20:47 UTC, spelkey-ucd requested changes

2024-06-03 20:47 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +    _onEmployeeSelect(e, index) {
A couple of notes on `_onEmployeeSelect` method:
1. it needs to work for new approver types AND existing ones since they share the same form, so you also need to pass in the approver object e.g.  `_onEmployeeSelect(e, approverType, employeeIndex)` and then you would do `approverType.employees[employeeIndex] = emp`
2. You don't need the validationHandler - validations are handled at the `approverType` level, not individual employees
3. The `if( this.employeeIsSelected(emp) ) return` part is no good. The form should ALWAYS update the approverType.employees array.

2024-06-03 20:47 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +    this.index = this.index + 1;
`this.index = this.index + 1;` is not needed.

Your form should always render the number of items in `approver.employees` - absolutely no need to track this number in a separate property.

2024-06-03 20:47 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +  _onDeleteBar(e, index, approver){
all that the _onDeleteBar should be is:


```js
_onDeleteBar(employeeIndex, approverType) {
  if (!employeeIndex) {
    approverType.employees[0] = {};
  } else {
    approverType.employees.splice(employeeIndex, 1);
  }
  this.requestUpdate()
}
```

The rest is extraneous.

2024-06-03 20:47 UTC, spelkey-ucd commented on src/client/js/pages/admin/app-page-admin-line-items.js
there should be no edits on this page.

2024-06-03 20:47 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +  isEqual(obj1, obj2) {
`isEqual` can be removed.

2024-06-03 20:47 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +        const getApproverTypeId = e?.payload?.getApproverTypeId;
check your response. `e?.payload?.getApproverTypeId` should never exist.

based on what you define in your store, you want `e.data.approverTypeId`

2024-06-03 20:47 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +        approverType.employees = this.newEmployees;
lose the `newEmployees` property. just rely on what is within ` approverType.employees`

2024-06-03 20:47 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +        delete approverType.editing;
do not delete `approverType.editing` here. delete it only after the submission is successful - aka you want the editing view if there is 400 response and the form needs fixing.

2024-06-03 20:47 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +        this.newApproverType.employees = this.newEmployees;
again, all of your forms cannot share the same `newEmployees` array.

2024-06-03 20:47 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +      this.new = false;
when canceling your edits, you want to revert your changes to what is in the store:
```js
storeApproverType = this.AdminApproverTypeModel.store[query].find(at => at.approverTypeId === approver.approverTypeId);
      for( let prop in storeApproverType ) {
        approver[prop] = storeApproverType[prop];
      }

```

2024-06-03 20:47 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.js
> +  async _getApproverType(){
i dont think you use `_getApproverType` anywhere

2024-06-03 20:47 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.tpl.js
> +                <div ?hidden=${approver.systemGenerated || !emp} id="employee-edit-bar-${index}" class="field-container">
`employee-edit-bar-${index}` will not always be a unique id. do you even need an id?

2024-06-03 20:47 UTC, spelkey-ucd commented on src/client/js/components/app-approver-type.tpl.js
> +                  <a id="employee-link-${index}" @click=${e => this._onDeleteBar(e, index, approver)} class='icon-link double-decker'>
`employee-link-${index}` will not always be a unique id. do you even need an id?

2024-06-05 15:18 UTC, spelkey-ucd requested changes
Looks close enough for merging into dev. Clean up your code and resubmit. e.g.
- remove extraneous code
- remove commented out code
- remove debugging console logs
- make sure classes and all methods have docstrings

2024-06-11 13:35 UTC, merged