draft component added
UCDavisLibrary/ucdlib-travel pull request #50
Opened 2024-06-08 19:36 UTC by sbagg

#48 initial draft list component

2024-06-12 14:04 UTC, spelkey-ucd requested changes

2024-06-12 14:04 UTC, spelkey-ucd commented on src/client/scss/components/draft-list.scss
> +        width: 390px;
using fixed widths is usually bad! it means they will not size responsively, and can potentially break their containers.

2024-06-12 14:04 UTC, spelkey-ucd commented on src/client/scss/components/draft-list.scss
> +    .draftHeading {
be consistent with your class naming convention.

kebab-case is usually best.

2024-06-12 14:04 UTC, spelkey-ucd commented on src/client/js/components/app-draft-list.js
> +      existingDrafts: {type: Array}
you only need one property that contains all your drafts.

2024-06-13 20:28 UTC, spelkey-ucd requested changes

2024-06-13 20:28 UTC, spelkey-ucd commented on src/client/js/components/approval-request-draft-list.js
> +    this.drafts = {edit:[], initial:[]};
this should just be a single array.

2024-06-13 20:28 UTC, spelkey-ucd commented on src/client/js/components/approval-request-draft-list.js
> +    _onApprovalRequestsFetched(e) {
you seem to be way over thinking this.

it should just be 
```js
this.drafts = e.payload.data.filter(draft => draft.approvalRequestId !== this.excludeId);
```

if the `excludeId` property is not set, the filter method will have no effect.

2024-06-13 20:28 UTC, spelkey-ucd commented on src/client/js/components/approval-request-draft-list.tpl.js
> +      <div class='component-header'>
you dont need a custom class here.

use the [panel component](http://webstyleguide.ucdavis.edu/?p=molecules-panel) with the `panel--icon panel--icon-custom panel--icon-<brandcolor>` modifiers

2024-06-13 20:28 UTC, spelkey-ucd commented on src/client/scss/components/approval-request-draft-list.scss
You don't need a lot of these custom styles once you start using the panel component. 

as a general rule, you should use `rem` instead of `px`.  the theme uses standard sizes for things e.g. 1rem, .5rem, 2rem, etc.   so try to keep things standardized.

2024-06-14 00:10 UTC, sbagg commented on src/client/js/components/approval-request-draft-list.js
> +    _onApprovalRequestsFetched(e) {
I have a question on this.  When you click on a link the `e.payload.data` becomes just a single query of the asked for  id.  So when I exclude that id it becomes blank. How do I address that?

2024-06-17 15:26 UTC, merged