38 site wide banner
UCDavisLibrary/ucdlib-travel pull request #77
Opened 2024-07-09 17:24 UTC by mjwdavis

closes #75

2024-07-09 17:38 UTC, spelkey-ucd requested changes

2024-07-09 17:38 UTC, spelkey-ucd commented on src/client/js/components/site-wide-banner.js
If you are going the component route, go all the way. Have the component fetch the data, and not `app-main`

2024-07-09 17:38 UTC, spelkey-ucd commented on src/client/js/components/site-wide-banner.js
> +      bannerText: {type: String},
if `bannerText` is empty, show nothing.

2024-07-09 17:38 UTC, spelkey-ucd commented on src/lib/cork/models/SettingsModel.js
You should not need to modify the SettingsModel at all. If your `site_wide_banner` is empty, do not show the banner, which should be controlled from `site-wide-banner.tpl.js`

2024-07-09 20:00 UTC, mjwdavis commented on src/client/js/components/site-wide-banner.js
Per the request:

- Create new setting with app-main category for text of banner
- app-main element will fetch via settingsModel

2024-07-09 20:01 UTC, mjwdavis commented on src/client/js/components/site-wide-banner.js
> +      bannerText: {type: String},
Text is never empty since model always retrieves text.

2024-07-09 20:03 UTC, spelkey-ucd commented on src/client/js/components/site-wide-banner.js
> +      bannerText: {type: String},
not true. the model can return empty text.

2024-07-09 20:08 UTC, spelkey-ucd commented on src/client/js/components/site-wide-banner.js
Yes, because I was assuming you were not going to make a dedicated element for the banner, but since you did, you should follow that approach to its logical end: move your settings call into that file instead of having one foot in each solution.

2024-07-09 20:08 UTC, mjwdavis commented on src/client/js/components/site-wide-banner.js
> +      bannerText: {type: String},
so you're saying no default text in the settings model in this instance?

2024-07-09 20:09 UTC, spelkey-ucd commented on src/client/js/components/site-wide-banner.js
> +      bannerText: {type: String},
what would the default text say?

2024-07-09 20:42 UTC, mjwdavis commented on src/client/js/components/site-wide-banner.js
ok. moved everything back to app-main

2024-07-09 20:50 UTC, mjwdavis commented on src/lib/cork/models/SettingsModel.js
Settings model doesn't allow empty values, so I had to drop something there when referencing SettingsModel.getByKey. Let me know if you had something else in mind!

2024-07-09 21:16 UTC, spelkey-ucd requested changes

2024-07-09 21:16 UTC, spelkey-ucd commented on src/client/js/app-main.js
> +    this.SettingsModel.getByKey('site_wide_banner') != 'default' ? this.bannerText = this.SettingsModel.getByKey('site_wide_banner') : this.bannerText = '';
settings model allows for empty values if `default_value` flag is off.

2024-07-09 21:16 UTC, spelkey-ucd commented on src/client/js/app-main.js
> +    async getPageData(){
the app-main component isn't really a page, and there are no other data requests it is doing. To make it easier to read, just do the fetch in your `checkForSettingsData` method.

2024-07-11 15:56 UTC, spelkey-ucd approved these changes

2024-07-11 15:56 UTC, merged