Sb email notification
UCDavisLibrary/ucdlib-travel pull request #78
Opened 2024-07-18 00:02 UTC by sbagg

This is an initial working notification.  It is all functional just want to make sure if there is a better way of doing it.  I used this data setup below as how I imagine a payload would be inserted but it probably has too much information.  Let me know what changes are needed!  

`    let ar = await this.ApprovalRequestModel.query({revisionIds:[1]});

    let subject = `Requestor: {{requesterFullName}} Submitted Status`

    let content = `
    Hi {{requesterFirstName}},
    
    Your travel, training, or professional development request has been successfully submitted. 
    It has been sent to {{nextApproverFullName}} for approval.
    
    
    You may cancel, resubmit, or view the status of this request at anytime by going to the following url: 
    {{approvalRequestUrl}}
    `;

    const payload = {
      "emailContent": {
        from: 'ucdlib-travel@example.com',
        to: 'sabaggett@ucdavis.edu',
        subject: subject,
        text: content
      },
      "requests": {
        approvalRequest: ar.payload.data[0],
        reimbursementRequest: {},
        token: this.AuthModel.getToken().token,
        type: 'approval-requested'
      }
    }

    const promises = [

      this.NotificationModel.createNotificationComments(payload),
      this.NotificationModel.getNotificationHistory()

    ]
    const resolvedPromises = await Promise.allSettled(promises);
    return promiseUtils.flattenAllSettledResults(resolvedPromises);
  }

  /**
   * @description bound to NotificationModel notification-comments event
   * @param {Object} e - cork-app-utils event
   * @returns
   */
  _onNotificationComments(e) {
    if ( e.state !== 'loaded' ) return;

    console.log("Created Notification:", e);
  }

    /**
   * @description bound to NotificationModel notification-history event
   * @param {Object} e - cork-app-utils event
   * @returns
   */
     _onNotificationHistory(e) {
      if ( e.state !== 'loaded' ) return;
  
      console.log("Retrieved Notifications:", e);
    }
`

2024-07-18 16:28 UTC, spelkey-ucd requested changes
Based on the code you included in your comment, I think there might be a misunderstanding on how system emails will be generated. They will not be generated from the client (only the questions/comments will do that). Instead, they will be generated by the server when their respective events occur e.g. submission, approval, etc

2024-07-18 16:28 UTC, spelkey-ucd commented on src/lib/utils/emailLib/hydration.js
> +import fetch from 'node-fetch';
should not need fetch

2024-07-18 16:28 UTC, spelkey-ucd commented on src/lib/utils/emailLib/logging.js
> +import fetch from 'node-fetch';
should not need fetch

2024-07-18 16:28 UTC, spelkey-ucd commented on src/lib/utils/emailLib/nodemailer.js
> +import fetch from 'node-fetch';
should not need fetch

2024-07-18 16:28 UTC, spelkey-ucd commented on src/lib/utils/emailLib/logging.js
> +    const validation = await this.entityFields.validate(data, ['notification_id']);
logging is something that is entirely controlled by you (not the user), so you shouldn't need a validation step

2024-07-18 16:28 UTC, spelkey-ucd commented on src/lib/utils/emailLib/logging.js
> +    // start transaction
you do not need a transaction - they are only necessary if you are doing more than one sql query that need to be saved as a single commit.

2024-07-18 16:28 UTC, spelkey-ucd commented on src/lib/utils/emailLib/logging.js
> +    } else if( kwargs.archived ) {
archived?

2024-07-18 16:28 UTC, spelkey-ucd commented on src/lib/utils/emailLib/logging.js
> +    if( kwargs.request_ids ) {
should probably call it approval_request_ids.

also, looks like your code will fail if an empty array is passed through

2024-07-18 16:28 UTC, spelkey-ucd commented on src/lib/utils/emailLib/logging.js
> +    const query = `
what's your use case for returning the whole approval and reimbursement requests?

2024-07-29 21:45 UTC, sbagg commented
Here is some way of testing the commands I put it in the home page. Not how it will work in final

` let ar = await this.ApprovalRequestModel.query({revisionIds:[1]});
    let subject = `Sample Subject`;
    let content = `Sample Question`;

    const payloadSystem = {
      "requests": {
        approvalRequest: ar.payload.data[0],
        reimbursementRequest: {},
      }, //requests could be replaced with id
      notificationType: 'request' //notification type
    }

    const payloadComments = {
      "emailContent": {
        subject: subject,
        text: content
      }, //email content 
      "url": "approval-request/1", //url
      "requests": {
        approvalRequest: ar.payload.data[0],
        reimbursementRequest: {},
      }, //requests could be replaced with id
      notificationType: 'request' //notification type
    }



/* Get Page
      this.NotificationModel.createSystemNotification(payloadSystem),
      this.NotificationModel.createNotificationComments(payloadComments),
      this.NotificationModel.getNotificationHistory()
*/

   * @description bound to NotificationModel notification-systems event
   * @param {Object} e - cork-app-utils event
   * @returns
   */
   _onNotificationSystems(e) {
    if ( e.state !== 'loaded' ) return;

    console.log("Created Notification System:", e);
  }


  /**
   * @description bound to NotificationModel notification-comments event
   * @param {Object} e - cork-app-utils event
   * @returns
   */
  _onNotificationComments(e) {
    if ( e.state !== 'loaded' ) return;

    console.log("Created Notification Comments:", e);
  }

    /**
   * @description bound to NotificationModel notification-history event
   * @param {Object} e - cork-app-utils event
   * @returns
   */
   _onNotificationHistory(e) {
      if ( e.state !== 'loaded' ) return;
  
      console.log("Retrieved No:", e);
  }
`

2024-07-30 17:14 UTC, spelkey-ucd requested changes

2024-07-30 17:14 UTC, spelkey-ucd commented on src/lib/utils/emailLib/nodemailer.js
> +  async runEmail(message){
i dont think this is the right usage. [According to the docs](https://nodemailer.com/usage/), a promise is only returned if you are not using a callback, and we want to wait for the email to be sent.

so i think you just need a little try wrapper
```js
async runEmail(message){
  let out = {};
  try {
    out.info = await this.transporter.sendMail(message);
  } catch (error) {
    out.error = error;
  }
  return error;
}
```

2024-08-02 15:57 UTC, spelkey-ucd requested changes

2024-08-02 15:57 UTC, spelkey-ucd commented on src/lib/db-models/emailController.js
> +    if ( text && subject && from && serverConfig.email.enabled ) {
test for `to` too

2024-08-02 15:57 UTC, spelkey-ucd commented on src/lib/db-models/emailController.js
> +    return result;
you might just want to return `emailSent`

2024-08-02 15:57 UTC, spelkey-ucd commented on src/lib/db-models/emailController.js
> +    if ( bodyTemplate && subjectTemplate && from && serverConfig.email.enabled ) {
check for `to`

2024-08-02 15:57 UTC, spelkey-ucd commented on deploy/docker-compose.yaml
> +    environment:
without making change in `/deploy/templates`, this will be overwritten the next time `/deploy/cmds/generate-deployment-files.sh` is run

2024-08-02 15:57 UTC, spelkey-ucd commented on src/lib/db-models/emailController.js
> +      details: details,
lets set `from` and `to` in `details` object as well. that way, we can verify routing is working correctly even if we have `serverConfig.email.enabled` set to false.

2024-08-02 15:57 UTC, spelkey-ucd commented on src/lib/utils/emailLib/hydration.js
> +  return emp.emp.res.email;
` emp.emp.res.email;` will bring down the whole app if employee doesnt exist or if there is a network error.

2024-08-02 15:57 UTC, spelkey-ucd commented on src/lib/utils/emailLib/hydration.js
> +    return res.status(500).json({error: true, message: 'Error retrieving next approver email.'});
you can't call this here.
1. you dont have access to the `res` object, so this will crash the app
2. even if you did pass throught the `res` object, all code after this will still be executed (badness)

2024-08-02 15:57 UTC, spelkey-ucd commented on src/lib/utils/emailLib/hydration.js
> +async _getHrEmail(){
you already have a method for this in your settings class

2024-08-02 15:57 UTC, spelkey-ucd commented on src/lib/utils/emailLib/hydration.js
> +  const variables = content.split('${').slice(1).map(x => x.split('}')[0]);
dont need this anymore!

2024-08-02 15:57 UTC, spelkey-ucd commented on src/lib/utils/emailLib/logging.js
> +        reimbursement_request rr ON n.reimbursement_request_id = rr.reimbursement_request_id
dont need these left joins

2024-08-08 15:06 UTC, spelkey-ucd requested changes
probably the last request for changes, so after addressing my comments, make sure to clean up your code by:
1. removing any extraneous code
2. removing any commented-out code
3. make sure all classes and class methods have docstrings with accurate description and parameters

2024-08-20 18:51 UTC, spelkey-ucd requested changes

2024-08-20 18:51 UTC, spelkey-ucd commented on src/lib/db-models/emailController.js
> +    let result = await logging.addNotificationLogging(notification);
```
if (result.error){
  console.error('error logging notification', result)
}
```

2024-08-20 18:51 UTC, spelkey-ucd commented on src/lib/db-models/emailController.js
> +  formatDate(date = '') {
docstring

2024-08-20 18:51 UTC, spelkey-ucd commented on src/lib/db-models/emailController.js
> +  async getHistory(query={}){
docstring

2024-08-20 18:51 UTC, spelkey-ucd commented on src/lib/db-models/reimbursementRequest.js
> +    emailController.sendSystemNotification( payloadSubmitReimbursement.notificationType,
await

2024-08-20 18:51 UTC, spelkey-ucd commented on src/lib/db-models/reimbursementRequest.js
> +    let rr = this.get({reimbursementRequestIds: [reimbursementRequestId]});
1. await
2. handle error

2024-08-20 18:51 UTC, spelkey-ucd commented on src/lib/utils/emailLib/hydration.js
> +export default class Hydration {
doc string

2024-08-20 18:51 UTC, spelkey-ucd commented on src/lib/utils/emailLib/logging.js
> +class Logging {
docstring

2024-08-20 18:51 UTC, spelkey-ucd commented on src/lib/utils/emailLib/settings.js
> +  async _getEmail(){
docstring

2024-08-26 16:19 UTC, spelkey-ucd requested changes

2024-08-26 16:19 UTC, spelkey-ucd commented on src/lib/utils/applicationOptions.js
> +        brandColor: 'cabernet',
These are not approval status actions. move to own array.

2024-08-30 13:54 UTC, merged