54 character limit tracker component
UCDavisLibrary/ucdlib-travel pull request #81
Opened 2024-08-01 00:21 UTC by mjwdavis

for issue #54

2024-08-01 16:32 UTC, spelkey-ucd requested changes

2024-08-01 16:32 UTC, spelkey-ucd commented on src/client/js/components/character-limit-tracker.js
> +      this.color = 'red';
use brand color classes

2024-08-01 16:32 UTC, spelkey-ucd commented on src/client/js/components/character-limit-tracker.js
> + * @property {Object} approvalRequest - The approval request object
declare properties

2024-08-01 16:32 UTC, spelkey-ucd commented on deploy/db-entrypoint/004-settings.sql
Settings are not required here - limits are set by the database, which we do not give control to admins.

2024-08-01 16:32 UTC, spelkey-ucd commented on src/client/js/components/character-limit-tracker.js
> +    this.warningThreshold = 0;
warning threshold should be a percentage, not a character count. that way, we don't have to worry about setting the warningThreshold, unless we want to override its default value:
```html
        <character-limit-tracker 
          .value=${this.approvalRequest.comments} 
          .characterLimit=100>
        </character-limit-tracker>
```

2024-08-01 16:32 UTC, spelkey-ucd commented on src/client/js/components/character-limit-tracker.tpl.js
> +      .warningThreshold=${this.warningThreshold || 100}
you dont need to set properties on the div container. it doesn't achieve anything.

you just need:
```html
<div class=${this.color}>${this.message}</div>
```

2024-08-01 16:32 UTC, spelkey-ucd commented on src/client/js/components/character-limit-tracker.js
> +  _calculateWarningThreshold() {
method not being used.

2024-08-02 00:46 UTC, mjwdavis commented on deploy/db-entrypoint/004-settings.sql
no problem - how are we retrieving them from the database if not through the settings model? If you can direct me to another example in the app I can add it there.

2024-08-02 00:47 UTC, mjwdavis commented on src/client/js/components/character-limit-tracker.js
> +    this.warningThreshold = 0;
So, remove the warningThreshold property from the element?

2024-08-02 01:48 UTC, mjwdavis commented on src/client/js/components/character-limit-tracker.tpl.js
> +      .warningThreshold=${this.warningThreshold || 100}
this threw an error so I had to approach it differently
https://lit.dev/docs/components/styles/#styles-in-the-template

2024-08-02 13:41 UTC, spelkey-ucd commented on deploy/db-entrypoint/004-settings.sql
it will be hardcoded

2024-08-02 13:56 UTC, spelkey-ucd requested changes

2024-08-02 13:56 UTC, spelkey-ucd commented on src/client/js/components/character-limit-tracker.tpl.js
> +      .character-limit-tracker {
this approach will not work if you have multiple `character-limit-tracker` components on a single page, which we will. Since you are using the `MainDomElement` mixin, the shadowroot has been disabled. So, if you have multiple of these components on a page, all components will use the color value for the `.character-limit-tracker` class that is defined last.

use [sitefarm class colors](https://brand.library.ucdavis.edu/#brand-colors):
```html
<div class='double-decker'>component message</div>
```

2024-08-08 15:12 UTC, merged